auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: localhost
  path_prefix: /tmp/loki
  storage: #As opções mais famosas são S3, GCS ou filesystem (armazenamento local)
    filesystem: 
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

#Configuração para retenção dos dados no loki:
table_manager:
  retention_deletes_enabled: true #Habilita a retenção automática
  retention_period: 336h #Período de 14 dias.

#Configuração de ingestão dos dados no loki. 
schema_config:
  configs:
    - from: 2024-03-01
      store: tsdb #Tipo de armazenamento que será utilizado para os registros.
      object_store: filesystem #Tipo de armazenamento
      schema: v12
      index:
        prefix: index_
        period: 24h #Tempo de TTL do index.


# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/analytics/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false